
const URL = {
    Login: '/login',
    DashboardAdmin: '/dashboard-admin',
    ManageUser: '/admin/manage-user',
    DashboardManage: '/dashboard-manage',
    ManageOrder: '/manage-order',
    ManageOutbound: '/manage-outbound',
    ManageProduct: '/admin/manage-product',
    ManageCategory: '/admin/manage-category',
    ManageUnit: '/admin/manage-unit',
    ManageUnitConversion: '/admin/manage-unit-conversion',
    ManageWarehouse: '/admin/manage-warehouse',
    ManageInventory: '/manage-inventory',
    InboundRequest: '/purchase',
    ViewInboundRequest: '/purchase/view',
    EditInboundRequest: '/purchase/edit',
    OutboundRequest: '/sale',
    ViewOutboundRequest: '/sale/view',
    EditOutboundRequest: '/sale/edit',
    TransferRequest: '/transfer',
    ViewTransferRequest: '/transfer/view',
    EditTransferRequest: '/transfer/edit',
    Profile: '/profile',
    ChangePassword: '/change-password',
    ManageBin: "/manage-bin",
    TransferBin: "/transfer-bin",
    ManageStockCount: "/manage-stock-count",
    ViewBin: "/manager-bin/view",
}
export default URL;
