// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using warehouseManagement.Models;

#nullable disable

namespace warehouseManagement.Migrations
{
    [DbContext(typeof(WmsContext))]
    [Migration("20260427011410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF2760ADE460EA6E");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("warehouseManagement.Models.AdjustmentReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AdjustmentReasons", (string)null);
                });

            modelBuilder.Entity("warehouseManagement.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("RefType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Approval__3214EC079EEA8943");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("warehouseManagement.Models.ApprovalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ActionAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("ActionBy")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovalId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Approval__3214EC079D570F04");

                    b.HasIndex("ActionBy");

                    b.HasIndex("ApprovalId");

                    b.ToTable("ApprovalLogs");
                });

            modelBuilder.Entity("warehouseManagement.Models.Bin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("Code", "WarehouseId")
                        .IsUnique();

                    b.ToTable("Bins");
                });

            modelBuilder.Entity("warehouseManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07CCCEB394");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("warehouseManagement.Models.InboundItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InboundRequestId")
                        .HasColumnType("int");

                    b.Property<string>("LineNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ReceivedQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__InboundI__3214EC075798DABA");

                    b.HasIndex("InboundRequestId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("InboundItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.InboundRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RequestNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__InboundR__3214EC07AF35A290");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "RequestNo" }, "UQ__InboundR__33A869A4045CBE22")
                        .IsUnique()
                        .HasFilter("[RequestNo] IS NOT NULL");

                    b.ToTable("InboundRequests");
                });

            modelBuilder.Entity("warehouseManagement.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inventor__3214EC07F523929A");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "ProductId", "WarehouseId", "StoragePosition" }, "UQ_Product_Warehouse_Bin")
                        .IsUnique()
                        .HasFilter("[StoragePosition] IS NOT NULL");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("warehouseManagement.Models.OutboundItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LineNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OutboundRequestId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PickedQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Outbound__3214EC0700E162EE");

                    b.HasIndex("OutboundRequestId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("OutboundItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.OutboundRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RequestNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Outbound__3214EC0780210F71");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "RequestNo" }, "UQ__Outbound__33A869A40FF14DA6")
                        .IsUnique()
                        .HasFilter("[RequestNo] IS NOT NULL");

                    b.ToTable("OutboundRequests");
                });

            modelBuilder.Entity("warehouseManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC072D8DC5C3");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Sku" }, "UQ__Products__CA1ECF0D3196D262")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("warehouseManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC0783C615EE");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6625A8735")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockCountItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Difference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int");

                    b.Property<int>("StockCountSessionId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("StockCountSessionId", "ProductId", "StoragePosition")
                        .IsUnique()
                        .HasFilter("[StoragePosition] IS NOT NULL");

                    b.ToTable("StockCountItems", (string)null);
                });

            modelBuilder.Entity("warehouseManagement.Models.StockCountSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("CountNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CountNo")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockCountSessions", (string)null);
                });

            modelBuilder.Entity("warehouseManagement.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("RefType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockMov__3214EC072F62B318");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockTransferItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromStoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LineNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ReceivedQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ShippedQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockTransferRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ToStoragePosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockTra__3214EC07B8B4D4CA");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTransferRequestId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockTransferItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockTransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FromWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ToWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("TransferNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__StockTra__3214EC07DE6315E3");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ToWarehouseId");

                    b.HasIndex(new[] { "TransferNo" }, "UQ__StockTra__9548BE629861B165")
                        .IsUnique();

                    b.ToTable("StockTransferRequests");
                });

            modelBuilder.Entity("warehouseManagement.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Units__3214EC07DF9EB686");

                    b.HasIndex(new[] { "Code" }, "UQ__Units__A25C5AA767180E21")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("warehouseManagement.Models.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("FromUnitId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__UnitConv__3214EC07806BF8FC");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("FromUnitId");

                    b.HasIndex(new[] { "ProductId", "FromUnitId" }, "UQ_Product_FromUnit")
                        .IsUnique();

                    b.ToTable("UnitConversions");
                });

            modelBuilder.Entity("warehouseManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC071C4F9126");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4A48DD635")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("warehouseManagement.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Warehous__3214EC0768FE66B8");

                    b.HasIndex(new[] { "Code" }, "UQ__Warehous__A25C5AA7BBD28221")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("warehouseManagement.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__3F466844");

                    b.HasOne("warehouseManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__3E52440B");
                });

            modelBuilder.Entity("warehouseManagement.Models.ApprovalLog", b =>
                {
                    b.HasOne("warehouseManagement.Models.User", "ActionByNavigation")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ActionBy")
                        .HasConstraintName("FK__ApprovalL__Actio__0A9D95DB");

                    b.HasOne("warehouseManagement.Models.Approval", "Approval")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ApprovalId")
                        .HasConstraintName("FK__ApprovalL__Appro__09A971A2");

                    b.Navigation("ActionByNavigation");

                    b.Navigation("Approval");
                });

            modelBuilder.Entity("warehouseManagement.Models.Bin", b =>
                {
                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.Category", b =>
                {
                    b.HasOne("warehouseManagement.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Categorie__Paren__46E78A0C");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("warehouseManagement.Models.InboundItem", b =>
                {
                    b.HasOne("warehouseManagement.Models.InboundRequest", "InboundRequest")
                        .WithMany("InboundItems")
                        .HasForeignKey("InboundRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__InboundIt__Inbou__6D0D32F4");

                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany("InboundItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__InboundIt__Produ__6E01572D");

                    b.HasOne("warehouseManagement.Models.Unit", "Unit")
                        .WithMany("InboundItems")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_InboundItems_Unit");

                    b.Navigation("InboundRequest");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("warehouseManagement.Models.InboundRequest", b =>
                {
                    b.HasOne("warehouseManagement.Models.User", "ApprovedByNavigation")
                        .WithMany("InboundRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__InboundRe__Appro__6A30C649");

                    b.HasOne("warehouseManagement.Models.User", "CreatedByNavigation")
                        .WithMany("InboundRequestCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__InboundRe__Creat__693CA210");

                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("InboundRequests")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__InboundRe__Wareh__68487DD7");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.Inventory", b =>
                {
                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventori__Produ__5DCAEF64");

                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventori__Wareh__5EBF139D");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.OutboundItem", b =>
                {
                    b.HasOne("warehouseManagement.Models.OutboundRequest", "OutboundRequest")
                        .WithMany("OutboundItems")
                        .HasForeignKey("OutboundRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__OutboundI__Outbo__778AC167");

                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany("OutboundItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__OutboundI__Produ__787EE5A0");

                    b.HasOne("warehouseManagement.Models.Unit", "Unit")
                        .WithMany("OutboundItems")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_OutboundItems_Unit");

                    b.Navigation("OutboundRequest");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("warehouseManagement.Models.OutboundRequest", b =>
                {
                    b.HasOne("warehouseManagement.Models.User", "ApprovedByNavigation")
                        .WithMany("OutboundRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__OutboundR__Appro__74AE54BC");

                    b.HasOne("warehouseManagement.Models.User", "CreatedByNavigation")
                        .WithMany("OutboundRequestCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__OutboundR__Creat__73BA3083");

                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("OutboundRequests")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__OutboundR__Wareh__72C60C4A");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.Product", b =>
                {
                    b.HasOne("warehouseManagement.Models.Unit", "BaseUnit")
                        .WithMany("Products")
                        .HasForeignKey("BaseUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_BaseUnit");

                    b.HasOne("warehouseManagement.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__Catego__5165187F");

                    b.Navigation("BaseUnit");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockCountItem", b =>
                {
                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("warehouseManagement.Models.AdjustmentReason", "Reason")
                        .WithMany("StockCountItems")
                        .HasForeignKey("ReasonId");

                    b.HasOne("warehouseManagement.Models.StockCountSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("StockCountSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Reason");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockCountSession", b =>
                {
                    b.HasOne("warehouseManagement.Models.User", "ApprovedUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("warehouseManagement.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedUser");

                    b.Navigation("CreatedUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockMovement", b =>
                {
                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__StockMove__Produ__628FA481");

                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__StockMove__Wareh__6383C8BA");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockTransferItem", b =>
                {
                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany("StockTransferItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Produ__03F0984C");

                    b.HasOne("warehouseManagement.Models.StockTransferRequest", "StockTransferRequest")
                        .WithMany("StockTransferItems")
                        .HasForeignKey("StockTransferRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Stock__02FC7413");

                    b.HasOne("warehouseManagement.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransferItems_Unit");

                    b.Navigation("Product");

                    b.Navigation("StockTransferRequest");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockTransferRequest", b =>
                {
                    b.HasOne("warehouseManagement.Models.User", "ApprovedByNavigation")
                        .WithMany("StockTransferRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__StockTran__Appro__00200768");

                    b.HasOne("warehouseManagement.Models.User", "CreatedByNavigation")
                        .WithMany("StockTransferRequestCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Creat__7F2BE32F");

                    b.HasOne("warehouseManagement.Models.Warehouse", "FromWarehouse")
                        .WithMany("StockTransferRequestFromWarehouses")
                        .HasForeignKey("FromWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__FromW__7D439ABD");

                    b.HasOne("warehouseManagement.Models.Warehouse", "ToWarehouse")
                        .WithMany("StockTransferRequestToWarehouses")
                        .HasForeignKey("ToWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__ToWar__7E37BEF6");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.UnitConversion", b =>
                {
                    b.HasOne("warehouseManagement.Models.Unit", "BaseUnit")
                        .WithMany("UnitConversionBaseUnits")
                        .HasForeignKey("BaseUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_UnitConversions_BaseUnit");

                    b.HasOne("warehouseManagement.Models.Unit", "FromUnit")
                        .WithMany("UnitConversionFromUnits")
                        .HasForeignKey("FromUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_UnitConversions_FromUnit");

                    b.HasOne("warehouseManagement.Models.Product", "Product")
                        .WithMany("UnitConversions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UnitConversions_Product");

                    b.Navigation("BaseUnit");

                    b.Navigation("FromUnit");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("warehouseManagement.Models.User", b =>
                {
                    b.HasOne("warehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("Users")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("FK_Users_Warehouse");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("warehouseManagement.Models.AdjustmentReason", b =>
                {
                    b.Navigation("StockCountItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.Approval", b =>
                {
                    b.Navigation("ApprovalLogs");
                });

            modelBuilder.Entity("warehouseManagement.Models.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("warehouseManagement.Models.InboundRequest", b =>
                {
                    b.Navigation("InboundItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.OutboundRequest", b =>
                {
                    b.Navigation("OutboundItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.Product", b =>
                {
                    b.Navigation("InboundItems");

                    b.Navigation("Inventories");

                    b.Navigation("OutboundItems");

                    b.Navigation("StockMovements");

                    b.Navigation("StockTransferItems");

                    b.Navigation("UnitConversions");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockCountSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("warehouseManagement.Models.StockTransferRequest", b =>
                {
                    b.Navigation("StockTransferItems");
                });

            modelBuilder.Entity("warehouseManagement.Models.Unit", b =>
                {
                    b.Navigation("InboundItems");

                    b.Navigation("OutboundItems");

                    b.Navigation("Products");

                    b.Navigation("UnitConversionBaseUnits");

                    b.Navigation("UnitConversionFromUnits");
                });

            modelBuilder.Entity("warehouseManagement.Models.User", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("InboundRequestApprovedByNavigations");

                    b.Navigation("InboundRequestCreatedByNavigations");

                    b.Navigation("OutboundRequestApprovedByNavigations");

                    b.Navigation("OutboundRequestCreatedByNavigations");

                    b.Navigation("StockTransferRequestApprovedByNavigations");

                    b.Navigation("StockTransferRequestCreatedByNavigations");
                });

            modelBuilder.Entity("warehouseManagement.Models.Warehouse", b =>
                {
                    b.Navigation("InboundRequests");

                    b.Navigation("Inventories");

                    b.Navigation("OutboundRequests");

                    b.Navigation("StockMovements");

                    b.Navigation("StockTransferRequestFromWarehouses");

                    b.Navigation("StockTransferRequestToWarehouses");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
